version: "2"
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: true
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  eslint:
    enabled: true
    config:
      config: eslint.config.mjs
exclude_patterns:
- "dist/"
- "node_modules/"
- "*.min.js"
- "webpack.config.js"
