extends:
  - airbnb-base
  - plugin:testing-library/react
  - plugin:jest-dom/recommended

env:
  browser: true
  es2021: true
  jest: true

parserOptions:
  ecmaVersion: 'latest'
  sourceType: 'module'

rules:
  'max-len': ['error', { code: 100, ignoreUrls: true, ignoreStrings: true, ignoreTemplateLiterals: true }]
  'no-trailing-spaces': 'error'
  'arrow-parens': ['error', 'as-needed']
  'comma-dangle': ['error', 'always-multiline']
  'operator-linebreak': ['error', 'before']
  'no-await-in-loop': 'off'
  'no-restricted-syntax': 'off'
  'class-methods-use-this': 'off'
  'import/order': 'off'
  'no-plusplus': 'off'
  'no-continue': 'off'
  'no-unused-vars': ['error', { argsIgnorePattern: '^_' }]
  'no-shadow': 'off'
  'no-alert': 'off'
  'no-use-before-define': 'off'
  'prefer-destructuring': 'off'
  'object-curly-newline': 'off'
  'testing-library/prefer-screen-queries': 'off'
  'import/no-extraneous-dependencies': ['error', { devDependencies: ['**/*.test.js', '**/*.spec.js', '**/webpack.*.js'] }]